execute: 
  app: app

spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: spring
    password: spring
    hikari:
      data-source-properties:
        useUnicode: true
        useJDBCCompliantTimezoneShift: true
        useLegacyDatetimeCode: true
        serverTimezone: JST
  flyway:
    enabled: true
    encoding: UTF-8
    validate-on-migrate: true
    clean-on-validation-error: true